In [36]:
!pip install numpy
!pip install matplotlib
!pip install tqdm

In [37]:
%matplotlib notebook
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import rc
from mpl_toolkits.mplot3d import axes3d
from matplotlib import cm
import matplotlib as mpl
from tqdm import tqdm

In [46]:
Min, Max, N = 0.,40.,11
x = np.linspace(Min,Max,N)
y = x.copy()
h = x[1]-x[0]

In [47]:
def h1(y):
    return 100.
def h2(y):
    return 0.
def h3(x):
    return 0.
def h4(x):
    return 0.

In [48]:
def InitT():
    
    T = np.zeros((N,N))
    
    T[0,:] = h1(y)
    T[-1,:] = h2(y)
    
    T[:,0] = h3(x)
    T[:,-1] = h4(x)
    
    return T

In [49]:
T = InitT()
print(T)

[[  0. 100. 100. 100. 100. 100. 100. 100. 100. 100.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]


In [38]:
v_0 = 1
v = 0.2
N = 51
h = 0.02
R = v_0*h/v

In [50]:
#los límites del obstáculo se fijaron entre los puntos:
x1 = 5
x2 = 25
y1 = 5
y2 = 30

In [40]:
x = np.linspace(0,1,N)
y = np.linspace(0,1,N)
X,Y = np.meshgrid(x,y)
u = np.zeros((N,N))
ω = np.zeros((N,N))

In [86]:
#Creamos la vorticidad de las fronteras
for i in tqdm(range(2500),ncols=100):
#fronteras en ω
  for i in range(x1, x2):
    ω[i, 0] = -2*((u[i, 1] - u[i, 0])/(h**2))
    ω[i, -1] = -2*((u[i, -2] - u[i, -1])/(h**2))

  for j in range(N-y2, N-y1 + 1):
    ω[i, j] = -2*((u[1, j] - u[0, j])/(h**2))
    ω[-1, j] = -2*((u[-2, j] - u[-1, j])/(h**2))
#fronteras en u
  for i in range(y1, y2+1):
    for j in range(x1, x2+1):
      u[x1, j] = 0 
      u[x2, j] = 0
      u[i, y1] = 0
      u[i, y2] = 0

100%|█████████████████████████████████████████████████████████| 2500/2500 [00:01<00:00, 1741.87it/s]


In [91]:
def vel(u, ω):
    for i in range(len(x)):
        u[-1,i] = u[-2,i] + h*v_0*y[-1] 
        u[0,i] = u[1,i]
        u[i,0] = u[i,1]
        u[i,-1] = u[i,-2]

In [92]:
#Con lo visto en clase:
def GetRelaxation(T, Nit = int(1e5), omega = 1.9, tolerancia = 1e-2):
    
    itmax = 0
    
    for it in tqdm(range(Nit)):
        
        dmax = 0.
        
        for i in range(1, len(x)-1):
            for j in range(1, len(y)-1):
                tmp = 0.25*(T[i+1,j]+T[i-1,j]+T[i,j+1]+T[i,j-1])
                r = omega*(tmp - T[i,j])
                
                T[i,j] += r
                
                if np.abs(r) > dmax:
                    dmax = r
       # print(T)
       # print(it)
        
        if np.abs(dmax) < tolerancia:
            print(it)
            itmax = it
            break
            
    return T,itmax

In [93]:
x,y = h*np.arange(N),h*np.arange(N)
X,Y = np.meshgrid(x,y)

In [94]:
fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(1,2,1)

c = ax.contourf(X, Y, u.T)
ax.set_title("Corriente")
ax.set_xlabel("$x(m)$")
ax.set_ylabel("$y(m)$")
fig.colorbar(c, ax = ax)
plt.savefig(r'gráfica 1.png')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


<IPython.core.display.Javascript object>

TypeError: ignored

In [95]:
fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(1,2,1)

c = ax.contourf(X, Y, ω.T)
ax.set_title("Velocidad")
ax.set_xlabel("$x(m)$")
ax.set_ylabel("$y(m)$")
plt.savefig(r'gráfica 2.png')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


<IPython.core.display.Javascript object>

TypeError: ignored

In [96]:
def GetGrad(T):
    
    M,N = T.shape
    
    u_ = np.zeros_like(T)
    v_ = np.zeros_like(T)
    
    for i in range(M):
        for j in range(N):
            
            if j == 0:
                v_[i,j] = T[i,j+1] - T[i,j]
            elif j == N - 1:
                v_[i,j] = T[i,j] - T[i,j-1]
            else:
                v_[i,j] = (T[i,j+1] - T[i,j-1])/2.
                
                
            if i == 0:
                u_[i,j] = T[i+1,j] - T[i,j]
            elif i == M - 1:
                u_[i,j] = T[i,j] - T[i-1,j]
            else:
                u_[i,j] = (T[i+1,j] - T[i-1,j])/2.
                
                
    return u_,v_

In [79]:
u1, v1 = GetGrad(u)
u1 = - u1
v1 = - v1

In [97]:
fig2 = plt.figure(figsize=(10,7))
ax = fig2.add_subplot(1,3,1)
ax.set_title('Corriente')
ax.streamplot(u1,v1,color='b',density=2)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  """Entry point for launching an IPython kernel.


<IPython.core.display.Javascript object>

TypeError: ignored

In [ ]:
fig = plt.figure(figsize=(10,6))
ax = fig.add_subplot(1,2,1)

c = ax.contourf(X, Y, ω.T)
ax.set_title("Velocidad")
ax.set_xlabel("$x(m)$")
ax.set_ylabel("$y(m)$")
ax.contour(ω)
plt.savefig(r'gráfica 3.png')